# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        smalltalk:
          - Pharo64-10
          # Waiting a 32-bit version of Pharo 90 before re-enabling this version
          #  - Pharo32-9.0
        smalltalk_config: [ .smalltalk.ston ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }}, ${{ matrix.smalltalk_config }} on ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}
        shell: bash
        timeout-minutes: 30
