# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        smalltalk:
          - Pharo64-10
        smalltalk_config: [ .smalltalk.ston ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }} 
    steps:
      - name: Setup Linux
        run: sudo apt install --yes libglib2.0-0
        shell: bash
        if: runner.os == 'Linux'
      - name: Setup OS X
        run: brew install gtk+3
        shell: bash
        if: runner.os == 'macOS'
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Test on Windows
        run: |
          curl https://files.pharo.org/vm/pharo-spur64-headless/Windows-x86_64/stable.zip --output vm.zip
          unzip -q vm.zip -d extracted
          curl http://files.pharo.org/vm/extra/gtk-glib-win64.zip  --output gtk-glib.zip
          unzip -q gtk-glib.zip -d extracted
          smalltalkci --vm extracted/Pharo.exe -s ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}
        if: runner.os == 'Windows'
        shell: bash
        timeout-minutes: 30
      - name: Test
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.smalltalk_config }}
        if: runner.os != 'Windows'
        shell: bash
        timeout-minutes: 30
